// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace JSONTest.iOS
{
	public partial class ScaleQuestionViewController : UIViewController
	{
		public ScaleQuestionViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
